import { createSlice } from '@reduxjs/toolkit';

// Theme definitions — each theme has: wallpaper, bubble colors, accent, quick reaction
export const CHAT_THEMES = {
  default: {
    name: 'Default',
    emoji: '💬',
    wallpaper: 'default',
    bubbleOwn: '#4A90E2',
    bubbleOwnText: '#FFFFFF',
    bubbleOther: '#FFFFFF',
    bubbleOtherText: '#1A202C',
    accent: '#4A90E2',
    quickReaction: '👍',
    gradient: 'linear-gradient(135deg, #4A90E2, #357ABD)',
  },
  ocean: {
    name: 'Ocean',
    emoji: '🌊',
    wallpaper: 'ocean',
    bubbleOwn: '#0EA5E9',
    bubbleOwnText: '#FFFFFF',
    bubbleOther: '#E0F2FE',
    bubbleOtherText: '#0C4A6E',
    accent: '#0EA5E9',
    quickReaction: '🌊',
    gradient: 'linear-gradient(135deg, #0EA5E9, #0284C7)',
  },
  sunset: {
    name: 'Sunset',
    emoji: '🌅',
    wallpaper: 'sunset',
    bubbleOwn: '#F97316',
    bubbleOwnText: '#FFFFFF',
    bubbleOther: '#FFF7ED',
    bubbleOtherText: '#7C2D12',
    accent: '#F97316',
    quickReaction: '🔥',
    gradient: 'linear-gradient(135deg, #F97316, #EA580C)',
  },
  aurora: {
    name: 'Aurora',
    emoji: '🌌',
    wallpaper: 'aurora',
    bubbleOwn: '#8B5CF6',
    bubbleOwnText: '#FFFFFF',
    bubbleOther: '#F5F3FF',
    bubbleOtherText: '#4C1D95',
    accent: '#8B5CF6',
    quickReaction: '✨',
    gradient: 'linear-gradient(135deg, #8B5CF6, #7C3AED)',
  },
  lavender: {
    name: 'Lavender',
    emoji: '💜',
    wallpaper: 'lavender',
    bubbleOwn: '#A855F7',
    bubbleOwnText: '#FFFFFF',
    bubbleOther: '#FAF5FF',
    bubbleOtherText: '#581C87',
    accent: '#A855F7',
    quickReaction: '💜',
    gradient: 'linear-gradient(135deg, #A855F7, #9333EA)',
  },
  forest: {
    name: 'Forest',
    emoji: '🌿',
    wallpaper: 'forest',
    bubbleOwn: '#22C55E',
    bubbleOwnText: '#FFFFFF',
    bubbleOther: '#F0FDF4',
    bubbleOtherText: '#14532D',
    accent: '#22C55E',
    quickReaction: '🌿',
    gradient: 'linear-gradient(135deg, #22C55E, #16A34A)',
  },
  love: {
    name: 'Love',
    emoji: '❤️',
    wallpaper: 'love',
    bubbleOwn: '#E11D48',
    bubbleOwnText: '#FFFFFF',
    bubbleOther: '#FFF1F2',
    bubbleOtherText: '#881337',
    accent: '#E11D48',
    quickReaction: '❤️',
    gradient: 'linear-gradient(135deg, #E11D48, #BE123C)',
  },
  midnight: {
    name: 'Midnight',
    emoji: '🌙',
    wallpaper: 'midnight',
    bubbleOwn: '#6366F1',
    bubbleOwnText: '#FFFFFF',
    bubbleOther: '#1E1B4B',
    bubbleOtherText: '#E0E7FF',
    accent: '#6366F1',
    quickReaction: '🌙',
    gradient: 'linear-gradient(135deg, #6366F1, #4F46E5)',
  },
  tiedye: {
    name: 'Tie-Dye',
    emoji: '🎨',
    wallpaper: 'tiedye',
    bubbleOwn: '#EC4899',
    bubbleOwnText: '#FFFFFF',
    bubbleOther: '#FDF2F8',
    bubbleOtherText: '#831843',
    accent: '#EC4899',
    quickReaction: '🎨',
    gradient: 'linear-gradient(135deg, #EC4899, #F97316, #8B5CF6)',
  },
  monochrome: {
    name: 'Monochrome',
    emoji: '♟️',
    wallpaper: 'monochrome',
    bubbleOwn: '#334155',
    bubbleOwnText: '#FFFFFF',
    bubbleOther: '#F8FAFC',
    bubbleOtherText: '#0F172A',
    accent: '#334155',
    quickReaction: '🖤',
    gradient: 'linear-gradient(135deg, #475569, #1E293B)',
  },
  cyberpunk: {
    name: 'Cyberpunk',
    emoji: '🤖',
    wallpaper: 'cyberpunk',
    bubbleOwn: '#F012BE',
    bubbleOwnText: '#FFFFFF',
    bubbleOther: '#111111',
    bubbleOtherText: '#01FF70',
    accent: '#F012BE',
    quickReaction: '⚡',
    gradient: 'linear-gradient(135deg, #F012BE, #7FDBFF, #01FF70)',
  },
  nature: {
    name: 'Nature',
    emoji: '🌲',
    wallpaper: 'nature',
    bubbleOwn: '#4D7C0F',
    bubbleOwnText: '#FFFFFF',
    bubbleOther: '#FEFCE8',
    bubbleOtherText: '#3F6212',
    accent: '#4D7C0F',
    quickReaction: '🌲',
    gradient: 'linear-gradient(135deg, #65A30D, #3F6212)',
  },
  cherryblossom: {
    name: 'Blossom',
    emoji: '🌸',
    wallpaper: 'cherryblossom',
    bubbleOwn: '#F472B6',
    bubbleOwnText: '#FFFFFF',
    bubbleOther: '#FDF2F8',
    bubbleOtherText: '#831843',
    accent: '#F472B6',
    quickReaction: '🌸',
    gradient: 'linear-gradient(135deg, #F472B6, #FDA4AF)',
  },
  hacker: {
    name: 'Terminal',
    emoji: '💻',
    wallpaper: 'hacker',
    bubbleOwn: '#22C55E',
    bubbleOwnText: '#000000',
    bubbleOther: '#000000',
    bubbleOtherText: '#4ADE80',
    accent: '#22C55E',
    quickReaction: '👾',
    gradient: 'linear-gradient(135deg, #000000, #16A34A)',
  },
  halloween: {
    name: 'Spooky',
    emoji: '🎃',
    wallpaper: 'halloween',
    bubbleOwn: '#EA580C',
    bubbleOwnText: '#FFFFFF',
    bubbleOther: '#2E1065',
    bubbleOtherText: '#F97316',
    accent: '#EA580C',
    quickReaction: '👻',
    gradient: 'linear-gradient(135deg, #EA580C, #4C1D95)',
  },
  valentine: {
    name: 'Valentine',
    emoji: '💝',
    wallpaper: 'valentine',
    bubbleOwn: '#BE123C',
    bubbleOwnText: '#FFFFFF',
    bubbleOther: '#FFF1F2',
    bubbleOtherText: '#881337',
    accent: '#BE123C',
    quickReaction: '💘',
    gradient: 'linear-gradient(135deg, #E11D48, #9F1239)',
  },
  winter: {
    name: 'Winter',
    emoji: '❄️',
    wallpaper: 'winter',
    bubbleOwn: '#38BDF8',
    bubbleOwnText: '#FFFFFF',
    bubbleOther: '#F0F9FF',
    bubbleOtherText: '#0369A1',
    accent: '#38BDF8',
    quickReaction: '⛄',
    gradient: 'linear-gradient(135deg, #7DD3FC, #0284C7)',
  },
  autumn: {
    name: 'Autumn',
    emoji: '🍂',
    wallpaper: 'autumn',
    bubbleOwn: '#D97706',
    bubbleOwnText: '#FFFFFF',
    bubbleOther: '#FFFBEB',
    bubbleOtherText: '#92400E',
    accent: '#D97706',
    quickReaction: '🍁',
    gradient: 'linear-gradient(135deg, #F59E0B, #B45309)',
  },
  galaxy: {
    name: 'Galaxy',
    emoji: '☄️',
    wallpaper: 'galaxy',
    bubbleOwn: '#312E81',
    bubbleOwnText: '#FFFFFF',
    bubbleOther: '#0F172A',
    bubbleOtherText: '#C7D2FE',
    accent: '#4338CA',
    quickReaction: '⭐',
    gradient: 'linear-gradient(135deg, #312E81, #1E1B4B, #0F172A)',
  },
  coffee: {
    name: 'Coffee',
    emoji: '☕',
    wallpaper: 'coffee',
    bubbleOwn: '#78350F',
    bubbleOwnText: '#FFFFFF',
    bubbleOther: '#FEF3C7',
    bubbleOtherText: '#451A03',
    accent: '#78350F',
    quickReaction: '🍩',
    gradient: 'linear-gradient(135deg, #92400E, #451A03)',
  },
  neon: {
    name: 'Neon',
    emoji: '⚡',
    wallpaper: 'neon',
    bubbleOwn: '#06B6D4',
    bubbleOwnText: '#FFFFFF',
    bubbleOther: '#2E1065',
    bubbleOtherText: '#22D3EE',
    accent: '#06B6D4',
    quickReaction: '✨',
    gradient: 'linear-gradient(135deg, #8B5CF6, #06B6D4)',
  },
};

const initialState = {
  mode: 'light',
  language: localStorage.getItem('language') || 'en',
  chatTheme: localStorage.getItem('chatTheme') || 'default',
};

const themeSlice = createSlice({
  name: 'theme',
  initialState,
  reducers: {
    setTheme: (state) => {
      state.mode = 'light';
      localStorage.setItem('theme', 'light');
      document.documentElement.classList.remove('dark');
    },
    setLanguage: (state, action) => {
      state.language = action.payload;
      localStorage.setItem('language', action.payload);
    },
    setChatTheme: (state, action) => {
      state.chatTheme = action.payload;
      localStorage.setItem('chatTheme', action.payload);
    },
  },
});

export const { setTheme, setLanguage, setChatTheme } = themeSlice.actions;
export default themeSlice.reducer;
